### ISSUE TITLE
[BUG] The balloons need some positioning when the player is facing right

### ISSUE THREAD

**Issue by MarianoAlipi** [MarianoAlipi/balloon-battle#7]
**Describe the bug**
The balloons have a weird offset when the player is facing right.

**To Reproduce**
1. Run the game
2. Select 'PLAY'
3. Walk right
4. See the werid positioning of the balloons.

**Comment by michelangelo404** [comment]
I have the latest version and I didn't notice anything about the weird position of the balloons

**Comment by MarianoAlipi** [comment]
Hi @michelangelo404!
I took a look and I think you're right! I will close this issue. While checking it, I also realized that issue #6 has resurfaced, so I reopened it.
Thanks for taking a look and if you'd like to contribute I'll be glad to help! :)
